version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./.database:/var/lib/postgresql
    env_file: ".env"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB_NAME
  app:
      image: plane-frames-gen-app:latest
      ports:
        - "8000:8000"
      volumes:
        - ./app:/work/app
      environment:
        - POSTGRES_HOSTNAME=postgres