import os

from dotenv import load_dotenv


MAX_SPEED_KM_S = 300000
MAX_SPEED_KM_H = 3600 * MAX_SPEED_KM_S
MIN_SPEED_KM_H = 0
MIN_LONGITUDE = 0
MAX_LONGITUDE = 180
MIN_LATITUDE = -90
MAX_LATITUDE = 90
MAX_ALT_METERS = 40000
MIN_ALT_METERS = 0
SCHEDULERS_INTERVAL_S = 1

load_dotenv()

POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_DB_NAME = os.getenv('POSTGRES_DB_NAME')
POSTGRES_HOSTNAME = os.getenv('POSTGRES_HOSTNAME')
POSTGRES_PORT = os.getenv('POSTGRES_PORT')
